### ISSUE TITLE
Tube Map - what do G18, B1, U09 etc mean?

### ISSUE THREAD

**Issue by edent** [davwheat/mastdatabase.co.uk#121]
E.g. on https://mastdatabase.co.uk/gb/london-underground-connectivity/

![Screenshot showing London Underground mobile connectivity - lots of strange symbols.](https://github.com/davwheat/mastdatabase.co.uk/assets/837136/d7abae6a-c229-4a5a-befd-7827a6c7c8dc)

I took a look around the site (and GitHub) but couldn't figure out what they meant.

Thanks for doing this - the website is a great resource.

**Comment by davwheat** [comment]
The G/U stand for GSM and UMTS, the names of the technologies behind 2G and 3G respectively. The number refers to the frequency, e.g., G18 is 1800 MHz GSM (2G) and U09 is 900 MHz UMTS (3G).

B refers to the [LTE (4G) frequency bands](https://en.wikipedia.org/wiki/LTE_frequency_bands). B1 is LTE Band 1, which is 2100 MHz. The same goes for "n", but for [5G NR frequency bands](https://en.wikipedia.org/wiki/5G_NR_frequency_bands). n1 is NR Band 1, which is 2100 MHz. These match up with what you can see on my [spectrum page for the UK](https://mastdatabase.co.uk/gb/spectrum/).

Where it has two of the same band (like O2's B40, B40), this means they have two 4G carriers present. LTE only supports a maximum of 20 MHz bandwidth, and O2 have 40 MHz of Band 40 (2300 MHz) spectrum, so operate two separate carriers of it.

Where an LTE band number already exists, the same NR band number will follow the same frequencies, but there are some NR bands that aren't in LTE. For example, there's n78 5G but no B78 LTE.

n77 or n78 is the 5G people recognise as "proper" 5G, with speeds of over a gigabit available on all UK networks using it.

Hope this helps! Let me know if you have any other questions.
