### ISSUE TITLE
Update Central line coverage on Tube map

### ISSUE THREAD

**Issue by atdr** [davwheat/mastdatabase.co.uk#210]
The tube map doesn't include the latest live coverage on the Central line (Bond Street to Chancery Lane) as shown on [TfL's December map](https://content.tfl.gov.uk/below-ground-4g-5g-tube-map-december-2023.pdf)

Thanks otherwise for a great resource!

**Comment by davwheat** [comment]
Thanks for pointing this out! Should be fixed in the next 5 mins or so.
