### ISSUE TITLE
[Coverage Map] EE has a new coverage map with different layer IDs

### ISSUE THREAD

**Issue by cg0** [davwheat/mastdatabase.co.uk#226]
EE have released a new coverage map page accessible from https://ee.co.uk/help/mobile-coverage-checker

Notable changes are a new colour theme and the 5G view not showing 4G anymore

Layers used are:
* 5g_new_ee
* 4g_new_ee
* 2g_new_ee

**Comment by davwheat** [comment]
note to self: https://github.com/davwheat/uk-mno-coverage-archive/commit/f386c824d7b99a4b9f8f4b4ce9a1b4001f273d48

**Comment by davwheat** [comment]
This has been scraped and is available in the 24 March 2024 copy of EE's coverage data, which should be live on the site in the next 15-20 mins.
